CC = gcc
CFLAGS = -Wall -Wextra -Werror

all: tcpclient tcpserver udpclient udpserver

tcpclient: tcpclient.c
    gcc tcpclient.c -o tcpclient

tcpserver: tcpserver.c
    gcc tcpserver.c -o tcpserver
